# Generated by Django 3.2.5 on 2021-08-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
            ],
            options={
                'unique_together': {('list', 'text')},
            },
        ),
    ]
